---
name: Build and push image to ECR
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push-image-to-ecr:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract tag
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        if [[ -z "$TAG" ]]; then
          echo "Failed to extract TAG from GITHUB_REF"
          exit 1
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Extracted TAG: $TAG"

    - name: Login to ECR
      uses: jwalton/gh-ecr-login@v3
      with:
        region: ${{ secrets.AWS_REGION }}
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build image
      run: |
        docker build -t ip812/go-template:${{ env.TAG }} .

    - name: Tag and Push to ECR
      run: |
        set -e

        echo "Tagging image..."
        docker tag ip812/go-template:${{ env.TAG }} 678468774710.dkr.ecr.eu-central-1.amazonaws.com/ip812/go-template:${{ env.TAG }}

        echo "Pushing image to ECR..."
        docker push 678468774710.dkr.ecr.eu-central-1.amazonaws.com/ip812/go-template:${{ env.TAG }}

  update-image:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update image
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "ip812/infra"
          event-type: update-image
          client-payload: |
            {
              "image_name": "678468774710.dkr.ecr.eu-central-1.amazonaws.com/ip812/go-template",
              "image_tag": "${{ github.ref_name }}",
              "commit_url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }
